import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from app.core.storage import JsonStateStore
from app.services.demo import SCENARIO_ENDPOINTS
from app.services.launch_checklist import EVAL_COMMANDS, EXPECTED_ARTIFACTS
from app.services.portfolio import DEMO_COMMANDS, JD_EVIDENCE


RELEASE_VERIFICATION_COMMANDS = [
    *EVAL_COMMANDS,
    (
        r'rg "release/quality-gate|release/publish-pack|Release Candidate|'
        r'Publish Pack|release_packs|release gate" app dashboard docs README.md tests scripts'
    ),
    (
        r"Get-ChildItem -Recurse -File data\release_packs -ErrorAction SilentlyContinue "
        r"| Select-Object FullName,Length,LastWriteTime"
    ),
]

EXPECTED_OUTPUTS = [
    "pytest exits 0 with the API, service, artifact, replay, policy, KB, leadership, portfolio, and release tests passing.",
    "ruff exits 0 for app, tests, dashboard, and scripts.",
    "app.evals.run_eval prints deterministic local evaluation metrics and a passing summary.",
    "scripts/demo_run.py prints release gate status/score plus the Publish Pack Markdown/JSON paths.",
    "rg finds the release endpoints, Release Candidate wording, Publish Pack wording, and release_packs artifact path across code, docs, tests, and scripts.",
    "Get-ChildItem lists generated Markdown and JSON files under data\\release_packs.",
]

GITHUB_REPO_CHECKLIST = [
    "README quick start, demo flow, endpoint list, and local/mock scope are current.",
    "docs/api.md documents GET /release/quality-gate and POST /release/publish-pack.",
    "docs/architecture.md explains the ReleaseService boundary and local artifact folder.",
    "docs/evaluation.md lists the Release Candidate gate and Publish Pack verification expectations.",
    "GitHub Actions CI exists and runs pytest plus ruff in a fresh checkout.",
    ".gitignore excludes data/ so generated packs do not pollute commits.",
    "No Azure, OpenAI, Zendesk, Jira, Slack, or GitHub credentials are required for the demo path.",
]

KNOWN_LIMITATIONS = [
    "The quality gate reports local deterministic readiness; it does not execute GitHub Actions or publish a repository.",
    "Screenshots and manual reviewer notes are represented as placeholders for a human to fill after dashboard review.",
    "Generated data/release_packs artifacts are intentionally ignored and should be regenerated by reviewers.",
    "External integrations remain fake/local by design; production adapters would need separate credentials, contracts, and security review.",
]


class ReleaseService:
    def __init__(self, store: JsonStateStore, release_packs_dir: Path):
        self.store = store
        self.release_packs_dir = release_packs_dir
        self.repo_root = Path(__file__).resolve().parents[2]

    async def quality_gate(self) -> dict[str, Any]:
        state = await self.store.load()
        generated_at = datetime.now(timezone.utc).isoformat()
        coverage = {
            "ci": self._ci_coverage(),
            "docs": self._docs_coverage(),
            "tests": self._test_coverage(),
            "eval": self._eval_coverage(),
            "demo": self._demo_coverage(),
            "api": self._api_coverage(),
            "artifacts": self._artifact_coverage(),
        }
        blockers = self._blockers(coverage)
        warnings = self._warnings(coverage)
        score = self._score(coverage, blockers)
        status = "blocked" if blockers else "ready_with_warnings" if warnings else "ready"
        return {
            "generated_at": generated_at,
            "mode": "local-deterministic-release-candidate-gate",
            "title": "Release Candidate Quality Gate",
            "status": status,
            "score": score,
            "blockers": blockers,
            "warnings": warnings,
            "verification_checklist": self._verification_checklist(),
            "coverage": coverage,
            "endpoint_inventory": self._endpoint_inventory(),
            "artifact_coverage": coverage["artifacts"],
            "runtime_notes": self._runtime_notes(state),
            "publish_readiness": self._publish_readiness(status, score, blockers, warnings),
            "local_only_notes": [
                "Default runtime is local/mock and deterministic.",
                "No Azure, OpenAI, Zendesk, Jira, Slack, or GitHub API access is required.",
                "Generated release artifacts are written under ignored data/release_packs.",
            ],
        }

    async def export_publish_pack(self) -> dict[str, Any]:
        gate = await self.quality_gate()
        generated_at = datetime.now(timezone.utc)
        pack_id = f"release_publish_pack_{generated_at.strftime('%Y%m%d_%H%M%S')}"
        json_path = self.release_packs_dir / f"{pack_id}.json"
        markdown_path = self.release_packs_dir / f"{pack_id}.md"
        pack = {
            "pack_id": pack_id,
            "generated_at": generated_at.isoformat(),
            "title": "Release Candidate Publish Pack",
            "release_summary": self._release_summary(gate),
            "quality_gate": gate,
            "setup_commands": [
                r"python -m venv .venv",
                r".\.venv\Scripts\python.exe -m pip install -e "".[dev]""",
                r"copy .env.example .env",
            ],
            "demo_commands": DEMO_COMMANDS,
            "verification_commands": RELEASE_VERIFICATION_COMMANDS,
            "expected_outputs": EXPECTED_OUTPUTS,
            "endpoint_inventory": gate["endpoint_inventory"],
            "artifact_inventory": self._artifact_inventory(),
            "screenshots_manual_verification_placeholders": self._screenshot_placeholders(),
            "github_repo_checklist": GITHUB_REPO_CHECKLIST,
            "commit_push_readiness_notes": self._commit_push_notes(gate),
            "recruiter_review_notes": self._recruiter_notes(gate),
            "known_limitations": KNOWN_LIMITATIONS,
            "artifact_paths": {
                "release_publish_pack_markdown": str(markdown_path),
                "release_publish_pack_json": str(json_path),
            },
        }
        markdown = self._markdown(pack)
        self.release_packs_dir.mkdir(parents=True, exist_ok=True)
        json_path.write_text(json.dumps(pack, indent=2, default=str), encoding="utf-8")
        markdown_path.write_text(markdown, encoding="utf-8")
        return {
            "pack_id": pack_id,
            "format": "markdown+json",
            "json_path": str(json_path),
            "markdown_path": str(markdown_path),
            "gate_status": gate["status"],
            "gate_score": gate["score"],
            "pack": pack,
            "markdown": markdown,
        }

    def _ci_coverage(self) -> dict[str, Any]:
        workflows = sorted(str(path.relative_to(self.repo_root)) for path in (self.repo_root / ".github" / "workflows").glob("*.yml"))
        ci_text = "\n".join(self._read(path) for path in workflows)
        return {
            "status": "pass" if workflows and "pytest" in ci_text and "ruff" in ci_text else "fail",
            "workflow_files": workflows,
            "checks": {
                "github_actions_workflow": bool(workflows),
                "pytest_in_ci": "pytest" in ci_text,
                "ruff_in_ci": "ruff" in ci_text,
            },
        }

    def _docs_coverage(self) -> dict[str, Any]:
        required = ["README.md", "docs/api.md", "docs/architecture.md", "docs/evaluation.md", "docs/workflow.md"]
        tokens = ["Release Candidate", "Publish Pack", "release/quality-gate", "release/publish-pack", "release_packs"]
        files = []
        for path in required:
            text = self._read(path)
            files.append(
                {
                    "path": path,
                    "exists": bool(text),
                    "mentions_release": any(token in text for token in tokens),
                }
            )
        return {
            "status": "pass" if all(item["exists"] and item["mentions_release"] for item in files) else "warn",
            "files": files,
        }

    def _test_coverage(self) -> dict[str, Any]:
        test_text = self._read("tests/test_api.py")
        checks = {
            "quality_gate_test": "release/quality-gate" in test_text,
            "publish_pack_test": "release/publish-pack" in test_text,
            "artifact_assertions": "release_packs" in test_text,
        }
        return {
            "status": "pass" if all(checks.values()) else "warn",
            "checks": checks,
            "test_file": "tests/test_api.py",
        }

    def _eval_coverage(self) -> dict[str, Any]:
        path = "app/evals/run_eval.py"
        return {
            "status": "pass" if self._repo_path(path).exists() else "fail",
            "command": r".\.venv\Scripts\python.exe -m app.evals.run_eval",
            "file": path,
        }

    def _demo_coverage(self) -> dict[str, Any]:
        text = self._read("scripts/demo_run.py")
        checks = {
            "calls_quality_gate": "/release/quality-gate" in text,
            "calls_publish_pack": "/release/publish-pack" in text,
            "prints_gate_status": "Release gate:" in text,
            "prints_publish_pack_path": "Publish Pack:" in text,
        }
        return {
            "status": "pass" if all(checks.values()) else "warn",
            "checks": checks,
            "file": "scripts/demo_run.py",
        }

    def _api_coverage(self) -> dict[str, Any]:
        routes_text = self._read("app/api/routes.py")
        checks = {
            "quality_gate_route": "/release/quality-gate" in routes_text,
            "publish_pack_route": "/release/publish-pack" in routes_text,
            "protected_by_api_key": routes_text.count("dependencies=[Depends(require_api_key)]") >= 1,
        }
        return {
            "status": "pass" if all(checks.values()) else "fail",
            "checks": checks,
            "endpoint_count": len(self._endpoint_inventory()),
        }

    def _artifact_coverage(self) -> dict[str, Any]:
        artifacts = EXPECTED_ARTIFACTS
        rows = []
        for item in artifacts:
            directory = self._repo_path(item["directory"])
            latest = self._latest_paths(directory)
            rows.append(
                {
                    **item,
                    "ignored_local_artifact": item["directory"].startswith("data/"),
                    "directory_exists": directory.exists(),
                    "latest_paths": latest,
                    "generated_file_count": len(latest),
                }
            )
        return {
            "status": "pass",
            "release_pack_directory": "data/release_packs",
            "data_ignored_by_git": "data/" in self._read(".gitignore"),
            "artifacts": rows,
        }

    def _verification_checklist(self) -> list[dict[str, Any]]:
        return [
            {"name": "pytest", "command": RELEASE_VERIFICATION_COMMANDS[0], "expected": EXPECTED_OUTPUTS[0]},
            {"name": "ruff", "command": RELEASE_VERIFICATION_COMMANDS[1], "expected": EXPECTED_OUTPUTS[1]},
            {"name": "eval", "command": RELEASE_VERIFICATION_COMMANDS[2], "expected": EXPECTED_OUTPUTS[2]},
            {"name": "demo", "command": RELEASE_VERIFICATION_COMMANDS[3], "expected": EXPECTED_OUTPUTS[3]},
            {"name": "release text search", "command": RELEASE_VERIFICATION_COMMANDS[4], "expected": EXPECTED_OUTPUTS[4]},
            {"name": "release artifact listing", "command": RELEASE_VERIFICATION_COMMANDS[5], "expected": EXPECTED_OUTPUTS[5]},
        ]

    def _endpoint_inventory(self) -> list[dict[str, Any]]:
        endpoints = [
            ("GET", "/release/quality-gate", "Release Candidate quality gate", False),
            ("POST", "/release/publish-pack", "Write Release Candidate Publish Pack", True),
            ("GET", "/ops/smoke-matrix", "Launch smoke matrix", False),
            ("POST", "/ops/launch-checklist", "Launch checklist artifact", True),
            ("GET", "/portfolio/evidence-index", "Portfolio Evidence Index", False),
            ("POST", "/portfolio/interview-pack", "Interview Pack artifact", True),
            ("GET", "/incidents/postmortem-summary", "Postmortem RCA summary", False),
            ("POST", "/incidents/rca-pack", "Postmortem RCA artifact", True),
            ("POST", "/demo/evidence-pack", "Full demo evidence artifact", True),
            ("POST", "/ops/operator-readiness-pack", "Operator readiness artifact", True),
            ("GET", "/ops/daily-brief", "Executive Daily Ops Brief", False),
            ("POST", "/ops/daily-brief-pack", "Executive Daily Ops Brief artifact", True),
            ("GET", "/leadership/scorecard", "Leadership KPI scorecard", False),
            ("GET", "/knowledge/quality-audit", "KB readiness audit", False),
            ("GET", "/metrics/agent-performance", "Agent metrics", False),
            ("GET", "/audit/events", "Audit trail", False),
        ]
        scenario_only = sorted(set(SCENARIO_ENDPOINTS) - {f"{method} {path}" for method, path, _, _ in endpoints})
        rows = [
            {
                "method": method,
                "path": path,
                "endpoint": f"{method} {path}",
                "purpose": purpose,
                "writes_artifact": writes,
                "requires_api_key": True,
            }
            for method, path, purpose, writes in endpoints
        ]
        rows.extend(
            {
                "method": endpoint.split(" ", 1)[0],
                "path": endpoint.split(" ", 1)[1],
                "endpoint": endpoint,
                "purpose": "Covered by the deterministic demo scenario.",
                "writes_artifact": "report" in endpoint or "pack" in endpoint or "brief" in endpoint,
                "requires_api_key": True,
            }
            for endpoint in scenario_only
        )
        return rows

    def _runtime_notes(self, state: dict[str, Any]) -> dict[str, Any]:
        return {
            "local_mock_only": True,
            "state_counts": {
                "tickets": len(state.get("tickets", {})),
                "runs": len(state.get("runs", {})),
                "traces": len(state.get("traces", {})),
                "approvals": len(state.get("approvals", {})),
                "outbox": len(state.get("outbox", {})),
            },
            "credential_requirements": "none for default demo; API key is the deterministic local demo key",
            "ignored_runtime_root": "data/",
        }

    def _publish_readiness(
        self,
        status: str,
        score: int,
        blockers: list[str],
        warnings: list[str],
    ) -> dict[str, Any]:
        return {
            "ready_to_commit": not blockers and score >= 90,
            "ready_to_push": not blockers and score >= 90,
            "ready_for_recruiter_review": not blockers and score >= 90,
            "requires_manual_review": bool(warnings),
            "recommended_branch_prefix": "dev",
            "recommended_commit_message": "Add release candidate quality gate and publish pack",
            "status": status,
        }

    def _release_summary(self, gate: dict[str, Any]) -> str:
        return (
            "Release Candidate gate for a polished local-first GitHub portfolio project. "
            f"The current release gate status is {gate['status']} with score {gate['score']}. "
            "The pack gathers setup, demo, verification, endpoint, artifact, screenshot, GitHub checklist, "
            "commit/push, recruiter review, and limitation notes without requiring external services."
        )

    def _artifact_inventory(self) -> list[dict[str, Any]]:
        return self._artifact_coverage()["artifacts"]

    def _screenshot_placeholders(self) -> list[dict[str, str]]:
        return [
            {
                "surface": "FastAPI docs",
                "placeholder": "Add screenshot after opening http://localhost:8000/docs.",
            },
            {
                "surface": "Streamlit Release Pack tab",
                "placeholder": "Add screenshot after running streamlit and exporting the Publish Pack.",
            },
            {
                "surface": "Demo terminal output",
                "placeholder": "Add screenshot showing release gate status/score and Publish Pack paths.",
            },
            {
                "surface": "GitHub repository page",
                "placeholder": "Add screenshot after pushing README, docs, tests, and release feature.",
            },
        ]

    def _commit_push_notes(self, gate: dict[str, Any]) -> list[str]:
        notes = [
            "Review git status and avoid staging unrelated collaborator changes unless intentionally included.",
            "Run the Release Candidate verification command set before committing.",
            f"Use commit message: {gate['publish_readiness']['recommended_commit_message']}.",
            "Generated data/release_packs files are ignored and do not need to be committed.",
        ]
        if gate["warnings"]:
            notes.append("Warnings are publish notes, not blockers; fill screenshot placeholders manually after review.")
        return notes

    def _recruiter_notes(self, gate: dict[str, Any]) -> list[str]:
        return [
            f"Lead with the Release Candidate score: {gate['score']} ({gate['status']}).",
            f"Show local evidence coverage across {len(JD_EVIDENCE)} portfolio skill areas.",
            "Point reviewers to scripts/demo_run.py for the one-command local proof path.",
            "Open the Release Pack dashboard tab to show gate status, blockers/warnings, verification commands, and artifact path.",
            "Emphasize that the project is credential-free by default but preserves production-shaped controls.",
        ]

    def _blockers(self, coverage: dict[str, Any]) -> list[str]:
        blockers = []
        for name, item in coverage.items():
            if item["status"] == "fail":
                blockers.append(f"{name} coverage failed")
        if not coverage["artifacts"]["data_ignored_by_git"]:
            blockers.append("data/ is not ignored by git")
        return blockers

    def _warnings(self, coverage: dict[str, Any]) -> list[str]:
        warnings = []
        for name, item in coverage.items():
            if item["status"] == "warn":
                warnings.append(f"{name} coverage is present but should be reviewed")
        warnings.append("Screenshot placeholders require manual capture before a final portfolio README polish pass.")
        return warnings

    def _score(self, coverage: dict[str, Any], blockers: list[str]) -> int:
        if blockers:
            return max(0, 70 - (len(blockers) * 10))
        values = []
        for item in coverage.values():
            values.append(100 if item["status"] == "pass" else 85 if item["status"] == "warn" else 0)
        return round(sum(values) / len(values))

    def _latest_paths(self, directory: Path) -> list[str]:
        if not directory.exists():
            return []
        files = [path for path in directory.iterdir() if path.suffix in {".md", ".json"}]
        files.sort(key=lambda path: (path.stat().st_mtime, path.name), reverse=True)
        return [str(path) for path in files[:2]]

    def _read(self, relative_path: str) -> str:
        path = self._repo_path(relative_path)
        if not path.exists():
            return ""
        return path.read_text(encoding="utf-8")

    def _repo_path(self, relative_path: str) -> Path:
        return self.repo_root / relative_path

    def _markdown(self, pack: dict[str, Any]) -> str:
        gate = pack["quality_gate"]
        command_rows = [
            f"- `{command}`" for command in pack["verification_commands"]
        ]
        expected_rows = [f"- {item}" for item in pack["expected_outputs"]]
        endpoint_rows = [
            f"| `{row['endpoint']}` | {row['purpose']} | {row['writes_artifact']} |"
            for row in pack["endpoint_inventory"]
        ]
        artifact_rows = [
            (
                f"- {item['name']}: `{item['directory']}` via `{item['producer']}` "
                f"(latest: `{', '.join(item['latest_paths']) or 'not generated yet'}`)"
            )
            for item in pack["artifact_inventory"]
        ]
        screenshot_rows = [
            f"- {item['surface']}: {item['placeholder']}"
            for item in pack["screenshots_manual_verification_placeholders"]
        ]
        checklist_rows = [f"- {item}" for item in pack["github_repo_checklist"]]
        commit_rows = [f"- {item}" for item in pack["commit_push_readiness_notes"]]
        recruiter_rows = [f"- {item}" for item in pack["recruiter_review_notes"]]
        limitation_rows = [f"- {item}" for item in pack["known_limitations"]]
        warning_rows = [f"- {item}" for item in gate["warnings"]] or ["- none"]
        blocker_rows = [f"- {item}" for item in gate["blockers"]] or ["- none"]
        return "\n".join(
            [
                f"# Release Candidate Publish Pack: {pack['pack_id']}",
                "",
                "## Release Summary",
                pack["release_summary"],
                "",
                "## Release Gate",
                f"- Status: **{gate['status']}**",
                f"- Score: {gate['score']}",
                "- Local/mock only: true",
                "",
                "## Blockers",
                *blocker_rows,
                "",
                "## Warnings",
                *warning_rows,
                "",
                "## Setup Commands",
                *[f"- `{command}`" for command in pack["setup_commands"]],
                "",
                "## Demo Commands",
                *[f"- `{command}`" for command in pack["demo_commands"]],
                "",
                "## Verification Commands",
                *command_rows,
                "",
                "## Expected Outputs",
                *expected_rows,
                "",
                "## Endpoint Inventory",
                "| Endpoint | Purpose | Writes Artifact |",
                "| --- | --- | ---: |",
                *endpoint_rows,
                "",
                "## Artifact Inventory",
                *artifact_rows,
                "",
                "## Screenshots / Manual Verification Placeholders",
                *screenshot_rows,
                "",
                "## GitHub Repo Checklist",
                *checklist_rows,
                "",
                "## Commit / Push Readiness Notes",
                *commit_rows,
                "",
                "## Recruiter Review Notes",
                *recruiter_rows,
                "",
                "## Known Limitations",
                *limitation_rows,
                "",
            ]
        )
